#!/bin/sh
pngcrush -rem alla -reduce -brute $1 $1.crush
data=`python << EOF
import base64
with open('$1.crush') as f:
    print base64.b64encode(f.read()) 
EOF
`
echo -n -e $data|xsel -i -b
rm "$1.crush"
